### ISSUE TITLE
Make it easier to get a reference on an individual route

### ISSUE THREAD

**Issue by jonnay** [JerrySievert/bricks#2]
It would be nice if it were possible to get an existing instance of an existing appServerl route object, so that it would be possible to write a route that could be hot-swappable.   Perhaps appserver.addRoute could return an id that can be used to an appserver.getRoute() function call to return the route object, or even if the appserver.addRoute call returned the object itself.

That way it would be possible to change the handler in an already-running server.

**Comment by JerrySievert** [comment]
I've actually been considering that very thing - specifically to be able to reload changed functionality during run-time. In the meantime, you can augment routes live (not replace). You can see this in action with the bricks analytics package.

**Comment by JerrySievert** [comment]
changed return value for `addRoute()` to return `routeId`, and `removeRoute()` to remove routes.
